name: 'data_quality_showcase'
version: '1.0.0'
config-version: 2

profile: 'data_quality_showcase'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_quality_showcase:
    staging:
      +materialized: table
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
    elementary:
      +materialized: table
      +schema: elementary